projects:
  alagamap:
    schemaPath: src\graphql\schema.json
    includes:
      - src\api\graphql\**\*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: e77v4d3jovfqhmher27uyk5wza
        codeGenTarget: typescript
        generatedFileName: src\api\api.ts
        docsFilePath: src\api\graphql
        region: us-east-1
        maxDepth: 4
      endpoints:
        prod: >-
          https://xqjuigvtnngznh3ibcuiianknu.appsync-api.us-east-1.amazonaws.com/graphql
